package com.libertymutual.claimsmanagement.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;
@DynamoDbBean
public class GeneralInsurance {

    private String id;
    private String policyNumber;
    private String customerName;
    private LocalDate claimStartDate;
    private String estimatedAmount;
    private String claimReason;
    private String incidentDescription;
    public String claimStatus;
    public String claimOutcome;
    public BigDecimal payoutAmount;
    private List<String> taskList;
    private List<String> noteList;
    private LocalDate incidentDate; // Optional
    private String additionalDetails; // Optional


    public GeneralInsurance() {
    }

    public GeneralInsurance(String id, String policyNumber, String customerName, LocalDate claimStartDate, String estimatedAmount, String claimReason, String incidentDescription, String claimStatus, String claimOutcome, BigDecimal payoutAmount, List<String> taskList, List<String> noteList, LocalDate incidentDate, String additionalDetails) {
        this.id = id;
        this.policyNumber = policyNumber;
        this.customerName = customerName;
        this.claimStartDate = claimStartDate;
        this.estimatedAmount = estimatedAmount;
        this.claimReason = claimReason;
        this.incidentDescription = incidentDescription;
        this.claimStatus = claimStatus;
        this.claimOutcome = claimOutcome;
        this.payoutAmount = payoutAmount;
        this.taskList = taskList;
        this.noteList = noteList;
        this.incidentDate = incidentDate;
        this.additionalDetails = additionalDetails;
    }

    @DynamoDbPartitionKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public String getPolicyNumber() {
        return policyNumber;
    }

    public void setPolicyNumber(String policyNumber) {
        this.policyNumber = policyNumber;
    }
    @DynamoDBAttribute
    public String getCustomerName() {
        return customerName;
    }

    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }
    @DynamoDBAttribute
    public LocalDate getClaimStartDate() {
        return claimStartDate;
    }

    public void setClaimStartDate(LocalDate claimStartDate) {
        this.claimStartDate = claimStartDate;
    }
    @DynamoDBAttribute
    public String getEstimatedAmount() {
        return estimatedAmount;
    }

    public void setEstimatedAmount(String estimatedAmount) {
        this.estimatedAmount = estimatedAmount;
    }
    @DynamoDBAttribute
    public String getClaimReason() {
        return claimReason;
    }

    public void setClaimReason(String claimReason) {
        this.claimReason = claimReason;
    }
    @DynamoDBAttribute
    public String getIncidentDescription() {
        return incidentDescription;
    }

    public void setIncidentDescription(String incidentDescription) {
        this.incidentDescription = incidentDescription;
    }
    @DynamoDBAttribute
    public LocalDate getIncidentDate() {
        return incidentDate;
    }
    @DynamoDBAttribute
    public void setIncidentDate(LocalDate incidentDate) {
        this.incidentDate = incidentDate;
    }
    @DynamoDBAttribute
    public String getAdditionalDetails() {
        return additionalDetails;
    }

    public void setAdditionalDetails(String additionalDetails) {
        this.additionalDetails = additionalDetails;
    }

    public String getClaimStatus() {
        return claimStatus;
    }

    public void setClaimStatus(String claimStatus) {
        this.claimStatus = claimStatus;
    }

    public String getClaimOutcome() {
        return claimOutcome;
    }

    public void setClaimOutcome(String claimOutcome) {
        this.claimOutcome = claimOutcome;
    }

    public BigDecimal getPayoutAmount() {
        return payoutAmount;
    }

    public void setPayoutAmount(BigDecimal payoutAmount) {
        this.payoutAmount = payoutAmount;
    }

    public List<String> getTaskList() {
        return taskList;
    }

    public void setTaskList(List<String> taskList) {
        this.taskList = taskList;
    }

    public List<String> getNoteList() {
        return noteList;
    }

    public void setNoteList(List<String> noteList) {
        this.noteList = noteList;
    }
}
